### ISSUE TITLE
frontend data display

### ISSUE THREAD

**Issue by aojiaooo** [cs130-w22/Group-B6#30]
## Epic
This epic is for all frontend core data display ui.

## User Stories
- [x] story #26 Home Page
- [ ] story #27 Analytics Page
- [x] story #28 Report Page
